name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎁 새로운 기능이 추가되었어요'
    labels: ['Type: Feature']
  - title: '🐞 기존 버그가 수정되었어요'
    labels: ['Type: Bug']
  - title: '🐬 코드를 개선했어요'
    labels:
      - 'Type: Improvement'
      - 'Type: Chore'
  - title: '⚙️ 프로젝트를 개선했어요'
    labels:
      - 'Type: Infra'
      - 'Type: Chore'
      - 'Type: Document'
      - 'Type: Fix'
  - title: '🚀 배포'
    labels:
      - 'deployment'

change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## 이번 버전의 변경사항은 아래와 같아요
  ---
  $CHANGES
no-changes-template: '변경사항이 없어요'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
