version: '3.8'

networks:
  production_network:
    name: production_network
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    networks:
      - production_network
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  spring-app-blue:
    build: .
    container_name: prod-blue
    networks:
      - production_network
    ports:
      - "8081:8080"
    volumes:
      - /home/ubuntu/app/log:/log
    depends_on:
      - redis

  spring-app-green:
    build: .
    container_name: prod-green
    networks:
      - production_network
    ports:
      - "8082:8080"
    volumes:
      - /home/ubuntu/app/log:/log
    depends_on:
      - redis
volumes:
  redis_data: